.virgl-rules:
  stage: layered-backends
  rules:
    - !reference [.gl-rules, rules]
    - !reference [.llvmpipe-rules, rules]
    - changes: &virgl_file_list
      - src/gallium/drivers/virgl/**/*
      - src/gallium/winsys/virgl/**/*
      when: on_success

.virgl-iris-manual-rules:
  stage: layered-backends
  retry: !reference [.scheduled_pipeline-rules, retry]
  rules:
    - !reference [.collabora-farm-manual-rules, rules]
    - !reference [.gl-manual-rules, rules]
    - changes:
        *virgl_file_list
      when: manual
    - !reference [.iris-manual-rules, rules]

.virgl-iris-rules-performance:
  stage: layered-backends
  retry: !reference [.scheduled_pipeline-rules, retry]
  rules:
    - !reference [.collabora-farm-manual-rules, rules]
    - !reference [.performance-rules, rules]
    - !reference [.gl-manual-rules, rules]
    - !reference [.llvmpipe-manual-rules, rules]
    - changes:
        *virgl_file_list
      when: manual
  allow_failure: true # see comment in .performance-rules, which we don't inherit this line from.
  variables:
    LAVA_JOB_PRIORITY: 40
    S3_ARTIFACT_NAME: "mesa-x86_64-default-release"
  needs:
    - kernel+rootfs_x86_64
    - debian-release


.virpipe-test:
  extends:
    - .test-gl
    - .virgl-rules
  variables:
    GALLIVM_PERF: nopt
    FLAKES_CHANNEL: "#virgl-ci"
  script:
    - xvfb-run --server-args='-noreset' bash -c ". $SCRIPTS_DIR/setup-test-env.sh && GALLIUM_DRIVER=virpipe install/deqp-runner.sh"

virpipe-on-gl:
  extends:
    - .deqp-test
    - .virpipe-test
  variables:
    DEQP_SUITE: virpipe-gl
    GPU_VERSION: virpipe-gl
    PIGLIT_PLATFORM: x11_egl
    DEQP_FRACTION: 4

.virgl-test:
  extends:
    - .test-gl
    - .virgl-rules
  variables:
    FLAKES_CHANNEL: "#virgl-ci"
    GALLIUM_DRIVER: "virgl"
    CROSVM_GALLIUM_DRIVER: "llvmpipe"
    CROSVM_GPU_ARGS: "gles=false,backend=virglrenderer,egl=true,surfaceless=true,width=1024,height=768"
    GALLIVM_PERF: "nopt,no_quad_lod"

virgl-on-gl:
  variables:
    DEQP_SUITE: virgl-gl
    GPU_VERSION: virgl-gl
    LP_NUM_THREADS: 1 # There will be FDO_CI_CONCURRENT Crosvm processes, so each should use a single thread
  parallel: 3
  tags:
    - kvm
  extends:
    - .deqp-test
    - .virgl-test

virgl-on-gles:
  variables:
    VIRGL_HOST_API: GLES
    DEQP_SUITE: virgl-gles
    GPU_VERSION: virgl-gles
    CROSVM_GPU_ARGS: "gles=true,backend=virglrenderer,egl=true,surfaceless=true,width=1024,height=768"
  extends:
    - virgl-on-gl

virgl-traces:
  extends:
    - .virgl-test
    - .piglit-traces-test
  variables:
    EGL_PLATFORM: "surfaceless"
    PIGLIT_REPLAY_DESCRIPTION_FILE: "${CI_PROJECT_DIR}/install/traces-virgl.yml"
    PIGLIT_REPLAY_DEVICE_NAME: "gl-virgl"
    PIGLIT_RESULTS: "virgl-replay"
    LD_LIBRARY_PATH: "${CI_PROJECT_DIR}/install/lib/"     # For Crosvm
  tags:
    - kvm
  script:
    - . "$SCRIPTS_DIR"/setup-test-env.sh
    # Use all threads for rendering and only run one job at a time
    # Couldn't get GitLab CI to correctly substitute the variable in the yaml
    - LP_NUM_THREADS=${FDO_CI_CONCURRENT} FDO_CI_CONCURRENT=1 install/crosvm-runner.sh install/piglit/piglit-traces.sh

.virgl-iris-test:
  extends:
    - .lava-piglit-traces:x86_64
  variables:
    DEVICE_TYPE: asus-cx9400-volteer
    BOOT_METHOD: depthcharge
    HWCI_KERNEL_MODULES: vhost_vsock
    HWCI_KVM: "true"
    HWCI_TEST_SCRIPT: "LP_NUM_THREADS=${FDO_CI_CONCURRENT} FDO_CI_CONCURRENT=1 /install/crosvm-runner.sh /install/piglit/piglit-traces.sh"
    GPU_VERSION: virgl
    DRIVER_NAME: virgl
    GALLIUM_DRIVER: virgl
    CROSVM_GALLIUM_DRIVER: iris
    CROSVM_GPU_ARGS: "gles=false,backend=virglrenderer,egl=true,surfaceless=true,width=1024,height=768"
    EGL_PLATFORM: surfaceless
    PIGLIT_PROFILES: replay
    PIGLIT_REPLAY_DESCRIPTION_FILE: "/install/traces-virgl-iris.yml"
    RUNNER_TAG: mesa-ci-x86-64-lava-asus-cx9400-volteer

virgl-iris-traces:
  extends:
    - .virgl-iris-test
    - .virgl-iris-manual-rules
  variables:
    PIGLIT_REPLAY_EXTRA_ARGS: "--keep-image --download-caching-proxy-url=${FDO_HTTP_CACHE_URI}"

virgl-iris-traces-performance:
  extends:
    - .virgl-iris-test
    - .virgl-iris-rules-performance
  variables:
    HWCI_FREQ_MAX: "true"
    PIGLIT_REPLAY_SUBCOMMAND: profile
    PIGLIT_REPLAY_LOOP_TIMES: 150
    PIGLIT_REPLAY_EXTRA_ARGS: "--download-caching-proxy-url=${FDO_HTTP_CACHE_URI}"

android-virgl-llvmpipe:
  extends:
    - .test-android
    - .virgl-rules
  variables:
    ANDROID_GPU_MODE: drm_virgl
    ANDROID_DRIVER: virtio_gpu
    GPU_VERSION: virgl-gl
    DEQP_SUITE: android-virgl
